# Generated by Django 3.1.4 on 2020-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sales_quantity',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
