# Generated by Django 3.1.4 on 2020-12-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201217_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_quantity',
        ),
    ]
