# Generated by Django 3.1.3 on 2020-12-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201220_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_id',
            new_name='discount',
        ),
    ]
