# Generated by Django 3.1.4 on 2020-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='DateOfBirth',
        ),
    ]
